import { SampleRecipe } from '../types/nutrition';

export const SAMPLE_RECIPES: SampleRecipe[] = [
  {
    id: 'moong-dal',
    name: 'Moong Dal Tadka (Yellow Lentil Curry)',
    category: 'Pulses & Legumes',
    description: 'Wholesome split yellow mung beans tempered with cumin, turmeric, and modest cold-pressed oil.',
    data: {
      food_name: 'Moong Dal Tadka',
      food_category: 'Pulses & Legumes',
      serving_size: 150,
      serving_unit: 'g',
      recipe_description: 'Cooked yellow mung dal tempered with cumin, tomatoes, and minimal ghee.',
      energy_kcal: 125,
      free_sugars: 0.8,
      saturated_fat: 1.1,
      sodium: 260,
      cholesterol: 2.0,
      protein: 8.8,
      fibre: 5.4,
      total_carbs: 18.5,
      complex_carbs: 12.3,
      mufa: 2.2,
      pufa: 1.4,
      iron: 3.4,
      calcium: 58,
      vitamin_a: 140,
      vitamin_c: 9.5,
      vitamin_d: 0,
      potassium: 410,
    }
  },
  {
    id: 'veg-khichdi',
    name: 'Vegetable & Millet Khichdi',
    category: 'Mixed Dishes',
    description: 'Balanced one-pot dish of foxtail millet, lentils, carrots, beans, and light spices.',
    data: {
      food_name: 'Vegetable & Millet Khichdi',
      food_category: 'Mixed Dishes',
      serving_size: 200,
      serving_unit: 'g',
      recipe_description: 'Nutritious mixture of foxtail millet, yellow moong dal, green peas, carrots.',
      energy_kcal: 145,
      free_sugars: 1.2,
      saturated_fat: 1.6,
      sodium: 290,
      cholesterol: 3.0,
      protein: 7.2,
      fibre: 4.8,
      total_carbs: 24.0,
      complex_carbs: 18.0,
      mufa: 2.4,
      pufa: 1.8,
      iron: 2.8,
      calcium: 46,
      vitamin_a: 280,
      vitamin_c: 12.0,
      vitamin_d: 0,
      potassium: 350,
    }
  },
  {
    id: 'palak-paneer',
    name: 'Palak Paneer (Spinach Cottage Cheese)',
    category: 'Dairy & Vegetables',
    description: 'Blanched spinach puree gently cooked with low-fat paneer cubes and Indian spices.',
    data: {
      food_name: 'Palak Paneer',
      food_category: 'Dairy & Vegetables',
      serving_size: 150,
      serving_unit: 'g',
      recipe_description: 'Pureed fresh spinach with cottage cheese cubes and cumin garlic tempering.',
      energy_kcal: 175,
      free_sugars: 1.5,
      saturated_fat: 4.2,
      sodium: 340,
      cholesterol: 18.0,
      protein: 11.5,
      fibre: 3.6,
      total_carbs: 7.5,
      complex_carbs: 2.4,
      mufa: 3.8,
      pufa: 1.1,
      iron: 4.1,
      calcium: 280,
      vitamin_a: 420,
      vitamin_c: 18.0,
      vitamin_d: 0.5,
      potassium: 390,
    }
  },
  {
    id: 'aloo-paratha',
    name: 'Aloo Paratha with Butter',
    category: 'Breads & Cereals',
    description: 'Whole wheat flatbread stuffed with spiced potato mash and topped with butter.',
    data: {
      food_name: 'Aloo Paratha with Butter',
      food_category: 'Breads & Cereals',
      serving_size: 120,
      serving_unit: 'g',
      recipe_description: 'Griddled wheat paratha filled with potato stuffing, served with table butter.',
      energy_kcal: 290,
      free_sugars: 2.0,
      saturated_fat: 5.8,
      sodium: 480,
      cholesterol: 20.0,
      protein: 5.5,
      fibre: 3.2,
      total_carbs: 38.0,
      complex_carbs: 32.8,
      mufa: 4.0,
      pufa: 1.5,
      iron: 1.8,
      calcium: 40,
      vitamin_a: 75,
      vitamin_c: 6.0,
      vitamin_d: 0,
      potassium: 220,
    }
  },
  {
    id: 'gulab-jamun',
    name: 'Gulab Jamun (Fried Sweet Dumpling)',
    category: 'Traditional Sweets',
    description: 'Deep-fried milk-solid dumplings soaked in thick aromatic sugar syrup.',
    data: {
      food_name: 'Gulab Jamun',
      food_category: 'Traditional Sweets',
      serving_size: 80,
      serving_unit: 'g',
      recipe_description: 'Khoa dumplings fried in clarified fat and immersed in hot sugar syrup.',
      energy_kcal: 380,
      free_sugars: 42.0,
      saturated_fat: 8.5,
      sodium: 110,
      cholesterol: 28.0,
      protein: 3.8,
      fibre: 0.2,
      total_carbs: 56.0,
      complex_carbs: 13.8,
      mufa: 4.2,
      pufa: 0.8,
      iron: 0.6,
      calcium: 95,
      vitamin_a: 45,
      vitamin_c: 0,
      vitamin_d: 0,
      potassium: 90,
    }
  }
];
