"""Nutrient thresholds, daily reference values, and configuration dictionaries."""
from typing import Dict, Any, List

# Algorithm metadata
ALGORITHM_METADATA = {
    "icmr_nin_2024": {
        "title": "ICMR-NIN 2024 Scientific Indian Recipe NutriScore",
        "version": "2024-ICMR/NIN/IFCT",
        "description": "Formulated strictly in compliance with ICMR-NIN 2024 Dietary Guidelines for Indians, Revised 2024 RDAs, and IFCT 2017 Databanks. Evaluates 11 demographic life stages, Indian cereal-pulse protein complementarity, 9 Essential Amino Acids, and chronic risk thresholds.",
        "negative_max": 100.0,
        "positive_max": 100.0,
        "span": 100.0,
    },
    "personalised_pndpq": {
        "title": "ICMR-NIN 2024 Scientific Indian Recipe NutriScore",
        "version": "2024-ICMR/NIN/IFCT",
        "description": "Formulated strictly in compliance with ICMR-NIN 2024 Dietary Guidelines for Indians, Revised 2024 RDAs, and IFCT 2017 Databanks. Evaluates 11 demographic life stages, Indian cereal-pulse protein complementarity, 9 Essential Amino Acids, and chronic risk thresholds.",
        "negative_max": 100.0,
        "positive_max": 100.0,
        "span": 100.0,
    },
    "full_39_nutrient": {
        "title": "IFCT 2017 Comprehensive 39-Component Model",
        "version": "2017-IFCT/NIN",
        "description": "Exhaustive model scoring all 39 food components in the Indian Food Composition Tables (IFCT 2017, National Institute of Nutrition - ICMR).",
        "negative_max": 50.0,
        "positive_max": 165.0,
        "span": 215.0,
    },
    "icmr_16_nutrient": {
        "title": "ICMR 16-Nutrient Baseline Model",
        "version": "1.0-INDB",
        "description": "Calibrated for Indian traditional recipes using ICMR-NIN Daily Values.",
        "negative_max": 50.0,
        "positive_max": 70.0,
        "span": 120.0,
    },
}

# Standard Reference Daily Values (Adult Moderate Work baseline based on ICMR-NIN 2020)
# Trace nutrients without specific ICMR-NIN values utilize FDA/WHO established daily values.
ICMR_DAILY_VALUES: Dict[str, Dict[str, Any]] = {
    # Macros
    "protein": {"dv": 54.0, "unit": "g", "source": "ICMR-NIN 2020 (0.83g/kg for 65kg reference man)"},
    "fibre": {"dv": 40.0, "unit": "g", "source": "ICMR-NIN 2020 (moderate work)"},
    
    # Minerals (11 components in INDB)
    "calcium": {"dv": 1000.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "iron": {"dv": 19.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "zinc": {"dv": 17.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "magnesium": {"dv": 440.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "potassium": {"dv": 3500.0, "unit": "mg", "source": "ICMR-NIN 2020 / WHO"},
    "phosphorus": {"dv": 1000.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "copper": {"dv": 2.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "manganese": {"dv": 4.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "selenium": {"dv": 40.0, "unit": "mcg", "source": "ICMR-NIN 2020"},
    "chromium": {"dv": 50.0, "unit": "mcg", "source": "ICMR-NIN 2020"},
    "molybdenum": {"dv": 45.0, "unit": "mcg", "source": "ICMR-NIN 2020 / FDA"},
    
    # Vitamins (13 components in INDB)
    "vitamin_a": {"dv": 1000.0, "unit": "mcg", "source": "ICMR-NIN 2020 (RAE)"},
    "vitamin_c": {"dv": 80.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "vitamin_d": {"dv": 20.0, "unit": "mcg", "source": "ICMR-NIN 2020 (800 IU)"},
    "vitamin_e": {"dv": 10.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "vitamin_k": {"dv": 55.0, "unit": "mcg", "source": "ICMR-NIN 2020"},
    "thiamin_b1": {"dv": 1.4, "unit": "mg", "source": "ICMR-NIN 2020"},
    "riboflavin_b2": {"dv": 1.6, "unit": "mg", "source": "ICMR-NIN 2020"},
    "niacin_b3": {"dv": 14.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "pantothenic_acid_b5": {"dv": 5.0, "unit": "mg", "source": "ICMR-NIN 2020 / FDA"},
    "vitamin_b6": {"dv": 2.0, "unit": "mg", "source": "ICMR-NIN 2020"},
    "biotin_b7": {"dv": 40.0, "unit": "mcg", "source": "ICMR-NIN 2020 / FDA"},
    "folate_b9": {"dv": 300.0, "unit": "mcg", "source": "ICMR-NIN 2020"},
    "vitamin_b12": {"dv": 2.5, "unit": "mcg", "source": "ICMR-NIN 2020"},
}

# Complete field definitions for the UI and validation
NUTRIENT_DEFINITIONS = [
    # --- NEGATIVE NUTRIENTS (Common to ICMR 16 & Full 39) ---
    {
        "key": "energy_kcal",
        "label": "Energy (Calories)",
        "unit": "kcal",
        "category": "negative",
        "description": "Energy density per 100g. Higher calorie concentration contributes to obesity risk.",
        "default": 0.0,
        "min": 0.0,
        "max": 1000.0,
        "required": True,
        "is_core": True,
    },
    {
        "key": "free_sugars",
        "label": "Free Sugars",
        "unit": "g",
        "category": "negative",
        "description": "Added sugars plus sugars naturally present in honey, syrups, and fruit juices.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": True,
        "is_core": True,
    },
    {
        "key": "saturated_fat",
        "label": "Saturated Fat",
        "unit": "g",
        "category": "negative",
        "description": "Saturated fatty acids linked to elevated LDL cholesterol levels.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": True,
        "is_core": True,
    },
    {
        "key": "sodium",
        "label": "Sodium",
        "unit": "mg",
        "category": "negative",
        "description": "Sodium salt content. High intake raises blood pressure and cardiovascular risk.",
        "default": 0.0,
        "min": 0.0,
        "max": 10000.0,
        "required": True,
        "is_core": True,
    },
    {
        "key": "cholesterol",
        "label": "Cholesterol",
        "unit": "mg",
        "category": "negative",
        "description": "Dietary cholesterol content per 100g.",
        "default": 0.0,
        "min": 0.0,
        "max": 3000.0,
        "required": True,
        "is_core": True,
    },

    # --- CORE POSITIVE MACRONUTRIENTS (ICMR 16 & Full 39) ---
    {
        "key": "protein",
        "label": "Protein",
        "unit": "g",
        "category": "positive_macro",
        "description": "Essential for muscle maintenance, cellular repair, and satiety.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": True,
        "is_core": True,
    },
    {
        "key": "fibre",
        "label": "Dietary Fibre",
        "unit": "g",
        "category": "positive_macro",
        "description": "Supports gut microbiome, healthy bowel motility, and glycemic regulation.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": True,
        "is_core": True,
    },
    {
        "key": "complex_carbs",
        "label": "Complex Carbohydrates",
        "unit": "g",
        "category": "positive_macro",
        "description": "Starch and wholesome non-sugar carbs providing sustained energy release.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": False,
        "is_core": True,
    },
    {
        "key": "total_carbs",
        "label": "Total Carbohydrates",
        "unit": "g",
        "category": "helper",
        "description": "Used to automatically derive Complex Carbs = Total Carbs - Free Sugars - Fibre.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": False,
        "is_core": True,
    },

    # --- BENEFICIAL FATTY ACIDS (ICMR 16 & Full 39) ---
    {
        "key": "mufa",
        "label": "MUFA (Monounsaturated Fat)",
        "unit": "g",
        "category": "positive_fatty_acid",
        "description": "Heart-healthy fats (oleic acid) found in olive, mustard, groundnut, and sesame oils.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": False,
        "is_core": True,
    },
    {
        "key": "pufa",
        "label": "PUFA (Polyunsaturated Fat)",
        "unit": "g",
        "category": "positive_fatty_acid",
        "description": "Essential polyunsaturated fatty acids contributing to metabolic and lipid balance.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": False,
        "is_core": True,
    },

    # --- CORE MICRONUTRIENTS (Included in ICMR 16 Model) ---
    {
        "key": "iron",
        "label": "Iron",
        "unit": "mg",
        "category": "positive_mineral",
        "description": "Prevents nutritional anaemia; crucial for oxygen transport and hemoglobin synthesis.",
        "default": 0.0,
        "min": 0.0,
        "max": 100.0,
        "required": False,
        "is_core": True,
    },
    {
        "key": "calcium",
        "label": "Calcium",
        "unit": "mg",
        "category": "positive_mineral",
        "description": "Essential for bone density, neuromuscular transmission, and cardiac function.",
        "default": 0.0,
        "min": 0.0,
        "max": 3000.0,
        "required": False,
        "is_core": True,
    },
    {
        "key": "vitamin_a",
        "label": "Vitamin A",
        "unit": "mcg",
        "category": "positive_vitamin",
        "description": "Supports vision, immune integrity, epithelial health, and gene expression.",
        "default": 0.0,
        "min": 0.0,
        "max": 10000.0,
        "required": False,
        "is_core": True,
    },
    {
        "key": "vitamin_c",
        "label": "Vitamin C",
        "unit": "mg",
        "category": "positive_vitamin",
        "description": "Potent antioxidant, promotes non-heme iron absorption and collagen formation.",
        "default": 0.0,
        "min": 0.0,
        "max": 2000.0,
        "required": False,
        "is_core": True,
    },
    {
        "key": "vitamin_d",
        "label": "Vitamin D (D2 + D3)",
        "unit": "mcg",
        "category": "positive_vitamin",
        "description": "Regulates calcium-phosphorus homeostasis and bone mineralization.",
        "default": 0.0,
        "min": 0.0,
        "max": 200.0,
        "required": False,
        "is_core": True,
    },
    {
        "key": "potassium",
        "label": "Potassium",
        "unit": "mg",
        "category": "positive_mineral",
        "description": "Counterbalances sodium, helps regulate healthy systemic blood pressure.",
        "default": 0.0,
        "min": 0.0,
        "max": 10000.0,
        "required": False,
        "is_core": True,
    },

    # --- ADDITIONAL EXTENDED MINERALS (Full 39-Nutrient Model) ---
    {"key": "zinc", "label": "Zinc", "unit": "mg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 100.0, "is_core": False},
    {"key": "magnesium", "label": "Magnesium", "unit": "mg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 2000.0, "is_core": False},
    {"key": "phosphorus", "label": "Phosphorus", "unit": "mg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 3000.0, "is_core": False},
    {"key": "copper", "label": "Copper", "unit": "mg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 20.0, "is_core": False},
    {"key": "manganese", "label": "Manganese", "unit": "mg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 20.0, "is_core": False},
    {"key": "selenium", "label": "Selenium", "unit": "mcg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 500.0, "is_core": False},
    {"key": "chromium", "label": "Chromium", "unit": "mcg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 500.0, "is_core": False},
    {"key": "molybdenum", "label": "Molybdenum", "unit": "mcg", "category": "positive_mineral", "default": 0.0, "min": 0.0, "max": 500.0, "is_core": False},

    # --- ADDITIONAL EXTENDED VITAMINS (Full 39-Nutrient Model) ---
    {"key": "vitamin_e", "label": "Vitamin E", "unit": "mg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 500.0, "is_core": False},
    {"key": "vitamin_k", "label": "Vitamin K (K1+K2)", "unit": "mcg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 1000.0, "is_core": False},
    {"key": "thiamin_b1", "label": "Thiamin (B1)", "unit": "mg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 20.0, "is_core": False},
    {"key": "riboflavin_b2", "label": "Riboflavin (B2)", "unit": "mg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 20.0, "is_core": False},
    {"key": "niacin_b3", "label": "Niacin (B3)", "unit": "mg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 100.0, "is_core": False},
    {"key": "pantothenic_acid_b5", "label": "Pantothenic Acid (B5)", "unit": "mg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 50.0, "is_core": False},
    {"key": "vitamin_b6", "label": "Vitamin B6", "unit": "mg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 50.0, "is_core": False},
    {"key": "biotin_b7", "label": "Biotin (B7)", "unit": "mcg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 500.0, "is_core": False},
    {"key": "folate_b9", "label": "Folate (B9)", "unit": "mcg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 2000.0, "is_core": False},
    {"key": "vitamin_b12", "label": "Vitamin B12", "unit": "mcg", "category": "positive_vitamin", "default": 0.0, "min": 0.0, "max": 100.0, "is_core": False},

    # --- PHYTONUTRIENT (Full 39-Nutrient Model) ---
    {"key": "carotenoids", "label": "Carotenoids", "unit": "mcg", "category": "positive_phytonutrient", "default": 0.0, "min": 0.0, "max": 50000.0, "is_core": False},

    # --- OFFICIAL NUTRI-SCORE SPECIFIC FIELD ---
    {"key": "fruit_veg_legume_pct", "label": "Fruits, Vegetables, Legumes, Nuts (%)", "unit": "%", "category": "positive_fvl", "default": 0.0, "min": 0.0, "max": 100.0, "is_core": False},
]
